name: publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: pack the project
        run: dotnet pack HikeRPG/HikeRPG/HikeRPG.csproj -c Release -o ./nupkg

      - name: get temporary nuget key
        uses: NuGet/login@v1
        id: login
        with:
          user: dkvasha123

      - name: push to nuget
        shell: bash
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate